import Image from 'next/image';
import Link from 'next/link';
import Icon from '@/components/Icon';
import PracticeCard from '@/components/PracticeCard';
import ArticleCard from '@/components/ArticleCard';
import { articles, practiceAreas, site } from '@/data/site';
export default function Home(){return <>
 <section className="hero"><div className="heroBg"><Image src="/images/hero-hukuk.webp" alt="" fill priority sizes="100vw"/></div><div className="heroShade"/><div className="container heroContent">
  <div className="heroCopy"><span className="kicker">İstanbul · Hukuk & Danışmanlık</span><h1>Hukuki meselelerde <em>özenli, anlaşılır ve sistemli</em> yaklaşım.</h1><p>Av. Vedat Karaman Hukuk Bürosu; uyuşmazlıkların hukuki çerçevesinin değerlendirilmesi, danışmanlık ve yargısal süreçlerin takibi alanlarında hizmet vermektedir.</p><div className="heroActions"><Link href="/iletisim" className="btn gold">İletişime Geç <Icon name="arrow" size={19}/></Link><Link href="/calisma-alanlari" className="btn ghost">Çalışma Alanları</Link></div></div>
  <div className="heroSeal"><div className="seal3d"><Icon name="scales" size={58}/><strong>Hukuk</strong><span>Danışmanlık · Temsil</span></div></div>
 </div></section>
 <section className="trustStrip"><div className="container trustGrid"><div><strong>{site.founded}</strong><span>Büronun kuruluş yılı</span></div><div><strong>İstanbul</strong><span>Sancaktepe merkezli</span></div><div><strong>11</strong><span>Çalışma alanı</span></div><div><strong>Bilgilendirme</strong><span>Şeffaf ve sade iletişim</span></div></div></section>
 <section className="section"><div className="container"><div className="sectionHead"><div><span className="eyebrow">Çalışma Alanları</span><h2>Hukukun farklı alanlarında yapılandırılmış hizmet.</h2></div><p>Her dosya kendi maddi vakıaları, delilleri ve güncel mevzuatı çerçevesinde değerlendirilir.</p></div><div className="practiceGrid">{practiceAreas.slice(0,6).map(x=><PracticeCard key={x.slug} item={x}/>)}</div><div className="center"><Link href="/calisma-alanlari" className="btn outline">Tüm çalışma alanlarını görüntüle</Link></div></div></section>
 <section className="section aboutBand"><div className="container split"><div className="portrait"><Image src="/images/vedat-karaman.webp" alt="Av. Vedat Karaman" fill sizes="(max-width: 900px) 100vw, 40vw"/></div><div className="aboutCopy"><span className="eyebrow">Hakkımızda</span><h2>Mesleki özen ve sorumluluk temelli hukuk hizmeti.</h2><p>Büronun kurucusu Av. Vedat Karaman, hukuk eğitimini 2018 yılında İstanbul Üniversitesi Hukuk Fakültesi’nde tamamlamıştır. Hukuk bürosu 2020 yılında İstanbul’da kurulmuştur.</p><p>Büro; başta iş hukuku ve kira/mülkiyet uyuşmazlıkları olmak üzere özel hukuk, kamu hukuku ve ticari uyuşmazlıklarda hukuki değerlendirme, danışmanlık ve temsil hizmetleri sunmaktadır.</p><Link href="/hakkimizda" className="textLink">Devamını Oku <Icon name="arrow" size={18}/></Link></div></div></section>
 <section className="section" id="makaleler"><div className="container"><div className="sectionHead"><div><span className="eyebrow">Makaleler</span><h2>Hukuki konulara ilişkin bilgilendirme notları.</h2></div><p>İçerikler yayımlandıkları tarihteki genel hukuki çerçeveye göre hazırlanmıştır; güncel mevzuat ayrıca kontrol edilmelidir.</p></div><div className="articleGrid">{articles.map(a=><ArticleCard key={a.slug} article={a}/>)}</div></div></section>
 <section className="ctaBand"><div className="container ctaInner"><div><span className="eyebrow">İletişim</span><h2>Dosyanızın hukuki çerçevesini görüşmek için iletişim bilgilerini kullanabilirsiniz.</h2></div><Link href="/iletisim" className="btn gold">İletişim Bilgileri <Icon name="arrow" size={19}/></Link></div></section>
 </>}
