import {createCipheriv,createDecipheriv,randomBytes,createHmac} from 'node:crypto';
import {isIP} from 'node:net';
import {sql} from './db.js';
export function sameOrigin(req){const origin=req.headers.get('origin');if(!origin)return false;if(origin===new URL(process.env.SITE_URL||req.url).origin)return true;if(process.env.NODE_ENV==='development'){try{const o=new URL(origin),r=new URL(req.url);return ['localhost','127.0.0.1'].includes(o.hostname)&&o.port===r.port&&o.protocol==='http:';}catch{return false;}}return false;}
export function clientIP(req){if(process.env.VERCEL){const ip=(req.headers.get('x-vercel-forwarded-for')||'').split(',')[0].trim();if(!isIP(ip))throw new Error('Güvenilir istemci adresi bulunamadı.');return ip;}if(process.env.NODE_ENV!=='production')return '127.0.0.1';throw new Error('Production dağıtımı Vercel güvenilir girişini gerektirir.');}
export function digest(value){return createHmac('sha256',process.env.ANALYTICS_SALT).update(value).digest('hex');}
export function encrypt(value){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',Buffer.from(process.env.APP_ENCRYPTION_KEY,'hex'),iv);return Buffer.concat([iv,cipher.update(value,'utf8'),cipher.final(),cipher.getAuthTag()]).toString('base64');}
export function decrypt(value){if(!value)return '';const b=Buffer.from(value,'base64');const decipher=createDecipheriv('aes-256-gcm',Buffer.from(process.env.APP_ENCRYPTION_KEY,'hex'),b.subarray(0,12));decipher.setAuthTag(b.subarray(-16));return Buffer.concat([decipher.update(b.subarray(12,-16)),decipher.final()]).toString('utf8');}
export async function rateLimit(key,limit=5,seconds=3600){const bucket=Math.floor(Date.now()/1000/seconds);const id=digest(`${key}:${bucket}`);const rows=await sql`INSERT INTO rate_limits(key,count,expires_at) VALUES(${id},1,now()+(${seconds} * interval '1 second')) ON CONFLICT(key) DO UPDATE SET count=rate_limits.count+1 RETURNING count`;return rows[0].count<=limit;}
export async function body(req,max=250000){if(Number(req.headers.get('content-length'))>max)throw new Error('İstek çok büyük.');if(!req.body)throw new Error('Boş istek.');const reader=req.body.getReader();const chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new Error('İstek çok büyük.');}chunks.push(value);}}finally{reader.releaseLock();}return JSON.parse(Buffer.concat(chunks,size).toString('utf8'));}
export const fail=(message,status=400)=>Response.json({error:message},{status});
